### ISSUE TITLE
trouble "extracting cards" from "Incremental Reading" article

### ISSUE THREAD

**Issue by HarshIceHummer** [aleksejrs/anki-2.0-vsa-and-ire#3]
Traceback (most recent call last):
File "C:\Users\Mahesh\Documents\Anki\addons\View_Size_Adjust.py", line 445, in callMe = lambda: self.quickAddCards(keyModel); File "C:\Users\Mahesh\Documents\Anki\addons\View_Size_Adjust.py", line 480, in quickAddCards self.setField(new_note, quickKeyModel['fieldName'], selectedText) File "C:\Users\Mahesh\Documents\Anki\addons\View_Size_Adjust.py", line 536, in setField ord = mw.col.models.fieldMap(note.model())[name][0] KeyError: u'Word'

Details here: https://anki.tenderapp.com/discussions/add-ons/8154-trouble-extracting-cards-from-incremental-reading-article

**Comment by aleksejrs** [comment]
I just got this problem. I haven't changed the target note type in the settings myself, but it was Basic-something instead of IRead2. When I switched it to IRead2, the problem disappeared.
